<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NagalakshmiSDET110" failures="39" tests="93" name="api.runner.TestRunner" time="282.176" errors="44" timestamp="2023-09-23T12:21:21 EDT" skipped="0">
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.254">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_invalid_program_id_in_program_module(Program_Stepdefinition.java:414)
at ✽.User receives 404 Not Found Status with message and boolean success details for invalid program id in program module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:134)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.055">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 4(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:43)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.206">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_batch_id_with_no_assignments_1(Assignment_Stepdefinition.java:546)
at ✽.User receives 404 Not Found Status with message and boolean success details for batch id with no assignments(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:120)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.020">
    <error message="usersInvalidModules.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: usersInvalidModules.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_missing_mandatory_fields(Users_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body with missing mandatory fields User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:15)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.198"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.211"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.026">
    <error message="Update_users.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Update_users.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_mandatory_fields(Users_Stepdefinition.java:293)
at ✽.User sends HTTPS Request and  request Body with mandatory fields User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:73)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.202"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.030">
    <error message="update_Role.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: update_Role.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body(Users_Stepdefinition.java:391)
at ✽.User sends HTTPS Request and  request Body User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:94)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.264">
    <failure message="expected [503] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_not_found_status(Batch_Stepdefinition.java:462)
at ✽.user receives 404 not found status(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:122)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.044">
    <error message="parameterValue cannot be null" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:515)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_with_mandatory_fields_program_description_program_name_program_status(Program_Stepdefinition.java:275)
at ✽.User sends HTTPS Request  and  request Body with mandatory fields. (program Description , program Name, program status)(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:71)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.032"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.048">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Batch_Stepdefinition.user_sends_https_request_and_request_body_with_existing_values_for_batch_module_from_excel(Batch_Stepdefinition.java:160)
at ✽.User sends HTTPS Request and  request Body with existing values for Batch Module from excel "BatchModule"(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:19)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.047">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 1(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:13)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.059">
    <error message="user_post.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: user_post.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_htt_ps_request_and_request_body_with_mandatory_and_additional_fields(Users_Stepdefinition.java:46)
at ✽.User sends HTTPs Request and request body with mandatory and additional fields User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.210">
    <error message="Failed to parse the JSON document" type="io.restassured.path.json.exception.JsonPathException">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_module_for_valid_batch_id_1(Assignment_Stepdefinition.java:463)
at ✽.User receives 200 OK Status with response body for Assignment Module for valid batch id(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:108)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_module_for_valid_batch_id_1(Assignment_Stepdefinition.java:463)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.042">
    <error message="parameterValue cannot be null" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:515)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_sends_https_request_with_valid_submission_id(Assignment_Submit_Stepdefinition.java:160)
at ✽.User sends HTTPS Request with valid submissionID(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:141)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.032">
    <error message="Update_UserRole.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Update_UserRole.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_program_batch_with_valid_user_id(Users_Stepdefinition.java:438)
at ✽.User sends HTTPS Request and  request Body with program batch with valid User Id User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:108)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.375">
    <error message="Failed to parse the JSON document" type="io.restassured.path.json.exception.JsonPathException">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_through_dynamic_variables_1(Assignment_Stepdefinition.java:65)
at ✽.User sends HTTPS Request and request Body for Assignment Module through dynamic variables(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:7)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_through_dynamic_variables_1(Assignment_Stepdefinition.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.226">
    <failure message="expected [503] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_ok_status_with_response_body(Batch_Stepdefinition.java:250)
at ✽.User receives 200 OK Status with response body.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:47)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.196">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:114)
at ✽.User receives 200 OK Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:70)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.248">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:114)
at ✽.User receives 200 OK Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.200"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.223">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_ok_status_with_updated_value_in_response_body_for_program_module(Program_Stepdefinition.java:258)
at ✽.User receives 200 OK Status with updated value in response body for program module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:62)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.029">
    <error message="AssignmentSubmit.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: AssignmentSubmit.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:93)
at ✽.User sends HTTPS Request and request Body for Assignment Submit Module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:33)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.232">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details(Program_Stepdefinition.java:493)
at ✽.User receives 404 Not Found Status with message and boolean success details Program(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:152)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.046">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 2(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:23)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.046">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 6(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:63)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.236">
    <failure message="expected [503] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_ok_status_with_updated_value_in_response_body(Batch_Stepdefinition.java:377)
at ✽.User receives 200 OK Status with updated value in response body.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:91)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.210">
    <failure message="expected [400] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_bad_request_status_with_message_and_boolean_success_details(Assignment_Submit_Stepdefinition.java:330)
at ✽.User receives 400 Bad Request Status with message and boolean success details Submit(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:124)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.241">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:114)
at ✽.User receives 200 OK Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:82)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.043">
    <error message="update_Role.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: update_Role.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_valid_user_id(Users_Stepdefinition.java:359)
at ✽.User sends HTTPS Request and  request Body with valid user id User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:87)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.198">
    <failure message="expected [503] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_ok_status_with_response_body(Batch_Stepdefinition.java:250)
at ✽.User receives 200 OK Status with response body.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:116)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.044">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 3(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:33)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.045">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Program_Stepdefinition.getAllData(Program_Stepdefinition.java:517)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_missing_mandatory_fields_from_excel_and(Program_Stepdefinition.java:294)
at ✽.User sends HTTPS Request  and request Body missing mandatory fields from excel "ProgramModule" and 3(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:114)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.207">
    <error message="Failed to parse the JSON document" type="io.restassured.path.json.exception.JsonPathException">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_for_getting_all_assignments_1(Assignment_Stepdefinition.java:271)
at ✽.User sends HTTPS Request for getting all assignments(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:83)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_for_getting_all_assignments_1(Assignment_Stepdefinition.java:271)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.032">
    <error message="parameterValue cannot be null" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:515)
at api.stepdefinitions.Batch_Stepdefinition.user_sends_https_request_with_valid_BATCH_NAME(Batch_Stepdefinition.java:304)
at ✽.User sends HTTPS Request with valid BATCH NAME(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:61)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.038">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 7(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:73)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.015">
    <error message="parameterValue cannot be null" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:515)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_sends_https_request_with_valid_user_id_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:194)
at ✽.User sends HTTPS Request with valid User Id for Assignment Submit Module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:57)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.042">
    <error message="AssignmentSubmit.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: AssignmentSubmit.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_submit_module_from_excel_and(Assignment_Submit_Stepdefinition.java:49)
at ✽.User sends HTTPS Request and  request Body for Assignment Submit Module from excel "Assignment_Submit_Module" and 1(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:13)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.228">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_program_module(Program_Stepdefinition.java:232)
at ✽.User receives 404 Not Found Status with message and boolean success details for program module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:53)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.078">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Program_Stepdefinition.getAllData(Program_Stepdefinition.java:517)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_for_progam_module_from_excel_and_with_missing_mandatory_fields(Program_Stepdefinition.java:141)
at ✽.User sends HTTPS Request and request Body for Progam Module from excel "ProgramModule" and 3 with missing mandatory fields(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:28)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.027">
    <error message="Update_InvalidRole.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Update_InvalidRole.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_missing_mandatory_fields_with_valid_user_id(Users_Stepdefinition.java:411)
at ✽.User sends HTTPS Request and  request Body with missing mandatory fields with valid user id User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:101)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.037">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_put_request_and_request_body_for_assignment_module_from_excel_and_1(Assignment_Stepdefinition.java:625)
at ✽.User sends PUT Request and request Body for Assignment Module from excel "AssignmentModule" and 8(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:132)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.195">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:133)
at ✽.User receives 404 Not Found Status with message and boolean success details for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:136)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.238">
    <failure message="expected [503] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_ok_status_with_response_body(Batch_Stepdefinition.java:250)
at ✽.User receives 200 OK Status with response body.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:76)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.210">
    <error message="Cannot invoke &quot;io.restassured.response.Response.then()&quot; because &quot;api.stepdefinitions.Batch_Stepdefinition.response1&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.then()" because "api.stepdefinitions.Batch_Stepdefinition.response1" is null
at api.stepdefinitions.Batch_Stepdefinition.user_receives_bad_request_status_with_message_and_boolean_success_details(Batch_Stepdefinition.java:184)
at ✽.User receives 400 Bad Request Status with message and boolean success details(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:108)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.196">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:114)
at ✽.User receives 200 OK Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:94)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.051">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Program_Stepdefinition.getAllData(Program_Stepdefinition.java:517)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_with_invalid_program_description_program_name_program_status_from_excel_and(Program_Stepdefinition.java:340)
at ✽.User sends HTTPS Request  and  request Body with Invalid (program Description , program Name, program status)from excel "ProgramModule" and 5(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:102)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.033">
    <error message="Update_InvalidUserRole.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Update_InvalidUserRole.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_missing_fields(Users_Stepdefinition.java:485)
at ✽.User sends HTTPS Request and  request Body with missing fields User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:122)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.036">
    <error message="AssignmentSubmit.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: AssignmentSubmit.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_submit_module_from_excel_and(Assignment_Submit_Stepdefinition.java:49)
at ✽.User sends HTTPS Request and  request Body for Assignment Submit Module from excel "Assignment_Submit_Module" and 1(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:23)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="1.183">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Program_Stepdefinition.getAllData(Program_Stepdefinition.java:517)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_for_progam_module_from_excel_and(Program_Stepdefinition.java:83)
at ✽.User sends HTTPS Request and request Body for Progam Module from excel "ProgramModule" and 1(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:7)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.230">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_ok_status_with_message(Program_Stepdefinition.java:384)
at ✽.User receives 200 Ok status with message(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:127)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.229">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:133)
at ✽.User receives 404 Not Found Status with message and boolean success details for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:64)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.203">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:133)
at ✽.User receives 404 Not Found Status with message and boolean success details for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:76)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.250">
    <failure message="expected [503] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_ok_status_with_response_body(Batch_Stepdefinition.java:250)
at ✽.User receives 200 OK Status with response body.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:41)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.217">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:133)
at ✽.User receives 404 Not Found Status with message and boolean success details for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:40)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.241">
    <failure message="expected [503] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details(Batch_Stepdefinition.java:290)
at ✽.User receives 404 Not Found Status with message and boolean success details(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:99)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.021">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_put_request_and_request_body_for_assignment_module_from_excel_and_for_negative_1(Assignment_Stepdefinition.java:666)
at ✽.User sends PUT Request and request Body for Assignment Module from excel "AssignmentModule" and 10 for negative(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:152)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.257">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_ok_status_with_response_body_for_program_module(Program_Stepdefinition.java:175)
at ✽.User receives 200 OK Status with response body for program module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:40)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.212">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:114)
at ✽.User receives 200 OK Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:112)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.035">
    <error message="usersInvalidModules.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: usersInvalidModules.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_missing_users_fields(Users_Stepdefinition.java:100)
at ✽.User sends HTTPS Request and request Body with missing users fields User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:22)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.049">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_and_request_body_for_assignment_module_from_excel__1and(Assignment_Stepdefinition.java:73)
at ✽.User sends HTTPS Request and request Body for Assignment Module from excel "AssignmentModule" and 5(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:53)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.034">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Program_Stepdefinition.getAllData(Program_Stepdefinition.java:517)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_to_update_progam_with_invalid_program_id_from_excel_and(Program_Stepdefinition.java:316)
at ✽.User sends HTTPS Request and request Body to update Progam with invalid program id from excel "ProgramModule" and 7(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.049">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Batch_Stepdefinition.user_sends_https_request_and_request_body_with_missing_fields_for_batch_module_from_excel(Batch_Stepdefinition.java:198)
at ✽.User sends HTTPS Request and  request Body with missing fields for Batch Module from excel "BatchModule"(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:29)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.100">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Batch_Stepdefinition.getAllData(Batch_Stepdefinition.java:55)
at api.stepdefinitions.Batch_Stepdefinition.user_sends_https_request_and_request_body_for_batch_module_from_excel_and(Batch_Stepdefinition.java:98)
at ✽.User sends HTTPS Request and  request Body for Batch Module from excel "BatchModule"(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.204">
    <failure message="expected [503] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details(Batch_Stepdefinition.java:290)
at ✽.User receives 404 Not Found Status with message and boolean success details(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:69)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.208">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_ok_status_with_message_for_valid_delete_request_1(Assignment_Stepdefinition.java:752)
at ✽.User receives 200 Ok status with message for valid delete request(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:163)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.036">
    <error message="update_InvalidUsers.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: update_InvalidUsers.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_missing_mandatory_fields(Users_Stepdefinition.java:321)
at ✽.User sends HTTPS Request  and request Body  (missing mandatory fields) User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:80)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.043"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.214">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_should_receives_not_found_status_with_error_message_1(Assignment_Stepdefinition.java:338)
at ✽.User should receives 404 Not Found status with error message(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:90)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="7.796">
    <failure message="expected [400] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_bad_request_status_with_message_and_boolean_success_details_for_program_module(Program_Stepdefinition.java:134)
at ✽.User receives 400 Bad Request Status with message and boolean success details for program module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.218">
    <error message="Failed to parse the JSON document" type="io.restassured.path.json.exception.JsonPathException">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_ok_status_with_updated_value_in_response_body_for_assignment_module_1(Assignment_Stepdefinition.java:591)
at ✽.User receives 200 OK Status with updated value in response body for Assignment Module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:126)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_ok_status_with_updated_value_in_response_body_for_assignment_module_1(Assignment_Stepdefinition.java:591)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.237">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_invaid_delete_assignment_id_1(Assignment_Stepdefinition.java:785)
at ✽.User receives 404 Not Found Status with message and boolean success details for invaid delete assignment id(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:169)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.197"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.224"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.026">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Assignment_Stepdefinition.getAllData(Assignment_Stepdefinition.java:838)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_put_request_and_request_body_for_assignment_module_from_excel_and_for_negative_1(Assignment_Stepdefinition.java:666)
at ✽.User sends PUT Request and request Body for Assignment Module from excel "AssignmentModule" and 9 for negative(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:142)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.212">
    <failure message="expected [400] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_bad_request_status_with_message_and_boolean_success_details(Assignment_Submit_Stepdefinition.java:330)
at ✽.User receives 400 Bad Request Status with message and boolean success details Submit(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:106)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.299"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.039">
    <error message="C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\User\eclipse-workspace\Team12-Api-CodeWarriors\src\test\resources\testdata\Team12-APICodeWarriors_TestData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at api.utilities.XLUtility.getRowCount(XLUtility.java:31)
at api.stepdefinitions.Program_Stepdefinition.getAllData(Program_Stepdefinition.java:517)
at api.stepdefinitions.Program_Stepdefinition.user_sends_https_request_and_request_body_missing_mandatory_fields_from_excel_and(Program_Stepdefinition.java:294)
at ✽.User sends HTTPS Request  and request Body missing mandatory fields from excel "ProgramModule" and 8(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:80)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.200">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:212)
at ✽.User receives 404 Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:52)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.212">
    <failure message="expected [503] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details(Batch_Stepdefinition.java:290)
at ✽.User receives 404 Not Found Status with message and boolean success details(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:83)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.183">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_invalid_batch_id_1(Assignment_Stepdefinition.java:523)
at ✽.User receives 404 Not Found Status with message and boolean success details for invalid batch id(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:114)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.215">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_submission_invalid_assignment_submit_module(Assignment_Submit_Stepdefinition.java:294)
at ✽.User receives 404 Not Found Status with message and boolean success details for submission invalid Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:88)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.034">
    <error message="Update_UserRole.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Update_UserRole.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_program_batch_with_invalid_user_id(Users_Stepdefinition.java:466)
at ✽.User sends HTTPS Request and  request Body with program batch with invalid User Id User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:115)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.209">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Submit_Stepdefinition.user_receives_ok_status_with_response_body_for_assignment_submit_module(Assignment_Submit_Stepdefinition.java:114)
at ✽.User receives 200 OK Status with response body for Assignment Submit Module.(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/5_Submission.feature:46)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.228">
    <failure message="expected [503] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [503] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Batch_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details(Batch_Stepdefinition.java:290)
at ✽.User receives 404 Not Found Status with message and boolean success details(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/2_Batch.feature:54)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.187">
    <failure message="expected [405] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [405] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_invaid_endpoint_for_assignment_module_1(Assignment_Stepdefinition.java:819)
at ✽.User receives 404 Not Found Status with message and boolean success details for invaid endpoint for assignment module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:175)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="0.030">
    <error message="Update_users.json (The system cannot find the file specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: Update_users.json (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at api.stepdefinitions.Users_Stepdefinition.user_sends_https_request_and_request_body_with_mandatory_and_additional_fields(Users_Stepdefinition.java:267)
at ✽.User sends HTTPS Request and  request Body with mandatory and additional  fields User(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/3_User.feature:66)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.250">
    <failure message="expected [404] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Assignment_Stepdefinition.user_receives_not_found_status_with_message_and_boolean_success_details_for_invalid_assignment_id_1(Assignment_Stepdefinition.java:425)
at ✽.User receives 404 Not Found Status with message and boolean success details for invalid assignment Id(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:102)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.253">
    <failure message="expected [200] but found [503]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [503]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at api.stepdefinitions.Program_Stepdefinition.user_receives_ok_status_with_response_body_for_program_module(Program_Stepdefinition.java:175)
at ✽.User receives 200 OK Status with response body for program module(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/1_Program.feature:47)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.210"/>
  <system-out/>
  <testcase classname="api.runner.TestRunner" name="runScenario" time="5.221">
    <error message="Failed to parse the JSON document" type="io.restassured.path.json.exception.JsonPathException">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_for_getting_all_assignments_by_assignment_id_1(Assignment_Stepdefinition.java:361)
at ✽.User sends HTTPS Request for getting all assignments by assignment id(file:///C:/Users/kodai/eclipse-workspace/RestAssured_Project/src/test/resources/features/4_Assignment.feature:95)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at api.stepdefinitions.Assignment_Stepdefinition.user_sends_https_request_for_getting_all_assignments_by_assignment_id_1(Assignment_Stepdefinition.java:361)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- api.runner.TestRunner -->
